workflows:
  android-release:
    name: Android Release
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build AAB
        script: flutter build appbundle --release --build-number=3
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
