/// Generated file. Do not edit.
/// This file is generated by the iFlutter
library;

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'stereo98';
  static const String PLUGIN_VERSION = '3.0.1+1';
}
